language: c

# Default environment: Container-based (sudo-less) Ubuntu Trusty 14.04.
os: linux
dist: trusty
sudo: false

# Default dependency installation step: nop intentionally.
# Jobs can add their own dependencies by redefinig the 'install' stage in the matrix below.
install: true

# Default job task: run tests as defined in the $OPT environment variable.
# Jobs can redefine the 'script' stage in the matrix below.
script:

# All the job definitions in the matrix.
matrix:
  include:
    - env:
        - JOBNAME="Build test"
      script: tools/build.py --dist
      addons:
        apt:
          packages: [pandoc]
  fast_finish: true
